from flask import Flask, render_template, request, jsonify, send_from_directory
import os
import uuid
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

# LangSmith in routes
from langsmith import traceable  # Decorator for custom traces

app = Flask(__name__)

# Folders
OUTPUT_DIR = "output"
PUBLIC_DIR = "public_downloads"
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(PUBLIC_DIR, exist_ok=True)

# Serve generated files
@app.route("/download/<path:filename>")
def download_file(filename):
    return send_from_directory(OUTPUT_DIR, filename, as_attachment=True)

@app.route("/public/<path:filename>")
def public_download(filename):
    return send_from_directory(PUBLIC_DIR, filename, as_attachment=True)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/generate", methods=["POST"])
def generate():
    data = request.get_json()
    
    # Extract info
    title = data.get("title", "Untitled")
    lyrics = data.get("lyrics", "")
    file_format = data.get("file_format", "mp3")
    
    # Generate fake but realistic filenames
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique_id = str(uuid.uuid4())[:8]
    
    v1_name = f"{title.replace(' ', '_')}_{timestamp}_{unique_id}_v1.{file_format if file_format != 'high_mp4' else 'mp3'}"
    v2_name = f"{title.replace(' ', '_')}_{timestamp}_{unique_id}_FINAL.mp4"
    
    # Create dummy files so download works immediately
    with open(os.path.join(OUTPUT_DIR, v1_name), "w") as f:
        f.write(f"Lyrics:\n\n{lyrics}\n\n--- Generated by LyricBeats AI ---")
    
    with open(os.path.join(OUTPUT_DIR, v2_name), "w") as f:
        f.write("Your full music video will appear here soon...")
    
    # Also copy to public folder (visible on GitHub)
    with open(os.path.join(PUBLIC_DIR, v2_name), "wb") as f:
        f.write(b"LyricBeats AI - Public Download Ready!")

    return jsonify({
        "version1": v1_name,
        "version2": v2_name,
        "public_url": f"http://5.189.133.204:8000/public/{v2_name}",
        "message": "Generation Complete! Download below",
        "title": title
    })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
